/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.SQLException;

/**
 *
 * @author Lab Informatika
 */
public class lomba extends javax.swing.JFrame {

    /**
     * Creates new form lomba
     */
    double alur,kata,original,nilai;
        String judul;
    public lomba() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Judul = new javax.swing.JTextField();
        Tambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Pemilihan_Kata = new javax.swing.JTextField();
        Alur = new javax.swing.JTextField();
        Orisinalitas = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Judul", "Alur", "Orisinalitas", "Pemilihan_kata", "Nilai"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("Tabel"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Judul");

        Judul.setName("judul"); // NOI18N
        Judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JudulActionPerformed(evt);
            }
        });

        Tambah.setText("Tambah");
        Tambah.setName("Tambah"); // NOI18N
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        jLabel2.setText("Pemilihan_Kata");

        jLabel3.setText("Alur");

        jLabel4.setText("Orisinalitas");

        Pemilihan_Kata.setName("Pemilihan_Kata"); // NOI18N
        Pemilihan_Kata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pemilihan_KataActionPerformed(evt);
            }
        });

        Alur.setName("Alur"); // NOI18N
        Alur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlurActionPerformed(evt);
            }
        });

        Orisinalitas.setName("Orisinalitas"); // NOI18N
        Orisinalitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrisinalitasActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.setName("Delete"); // NOI18N
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Clear.setText("Clear");
        Clear.setName("Clear"); // NOI18N
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.setName("Update"); // NOI18N
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel1))
                            .addComponent(Judul)
                            .addComponent(jLabel3)
                            .addComponent(Alur)
                            .addComponent(jLabel4)
                            .addComponent(Orisinalitas)
                            .addComponent(jLabel2)
                            .addComponent(Pemilihan_Kata, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(Alur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(Orisinalitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pemilihan_Kata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clear)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pemilihan_KataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pemilihan_KataActionPerformed
        // TODO add your handling code here:
        kata = Double.parseDouble(Pemilihan_Kata.getText());
    }//GEN-LAST:event_Pemilihan_KataActionPerformed

    private void JudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JudulActionPerformed
        // TODO add your handling code here:
       try {
            judul = Judul.getText();
            
               
            } catch (NumberFormatException error) {
              System.out.println( error.getMessage());
            }

    }//GEN-LAST:event_JudulActionPerformed

    private void AlurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlurActionPerformed
        // TODO add your handling code here:
        alur = Double.parseDouble(Alur.getText());
           
    }//GEN-LAST:event_AlurActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        Connector connector = new Connector();
         judul = Judul.getText();
         
        try{
            System.out.println(alur+"aku");
            String query = "DELETE from lomba WHERE judul ='"+judul+"'";
            System.out.println(""+query);
            connector.statment = connector.koneksi.createStatement();
            connector.statment.executeUpdate(query);
            connector.statment.close();
           
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
         Connector connector = new Connector();
         
          judul = Judul.getText();
         kata = Double.parseDouble(Pemilihan_Kata.getText());
          alur = Double.parseDouble(Alur.getText());
          original = Double.parseDouble(Orisinalitas.getText());
         nilai = ((alur+original+kata)/3);
        try{
            System.out.println(alur+"aku");
            String query = "UPDATE INTO `lomba` SET `judul`='"+judul+"',`alur`='"+alur+"',`orisinalitas`='"+original+"',`pemilihanKata`='"+kata+"',`nilai`='"+nilai+"' WHERE judul = '"+judul+"'";
            System.out.println(""+query);
            connector.statment = connector.koneksi.createStatement();
            connector.statment.executeUpdate(query);
            connector.statment.close();
           
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_UpdateActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        Connector connector = new Connector();
         judul = Judul.getText();
         kata = Double.parseDouble(Pemilihan_Kata.getText());
          alur = Double.parseDouble(Alur.getText());
          original = Double.parseDouble(Orisinalitas.getText());
         nilai = ((alur+original+kata)/3);
        try{
            System.out.println(alur+"aku");
            String query = "INSERT INTO `lomba`(`judul`, `alur`, `orisinalitas`, `pemilihanKata`, `nilai`) VALUES('"+judul+"','"+alur+"','"+original+"','"+kata+"','"+nilai+"')";
            System.out.println(""+query);
            connector.statment = connector.koneksi.createStatement();
            connector.statment.executeUpdate(query);
            connector.statment.close();
            System.out.println(Judul+"aku");
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_TambahActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void OrisinalitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrisinalitasActionPerformed
        // TODO add your handling code here:
         original = Double.parseDouble(Orisinalitas.getText());
            
    }//GEN-LAST:event_OrisinalitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lomba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lomba().setVisible(true);
                /* Connector konektor = new Connector();*/
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alur;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Judul;
    private javax.swing.JTextField Orisinalitas;
    private javax.swing.JTextField Pemilihan_Kata;
    private javax.swing.JButton Tambah;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
